"""Add Ignition Sequence fields to models

Revision ID: cc439d07b76b
Revises: c64bd9df0037
Create Date: 2025-06-15 00:56:59.240397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc439d07b76b'
down_revision = 'c64bd9df0037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rough_ideas_dump', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emotional_tag', sa.String(length=50), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hypothesis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('method', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expected_output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('risk_level')
        batch_op.drop_column('expected_output')
        batch_op.drop_column('method')
        batch_op.drop_column('hypothesis')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('emotional_tag')
        batch_op.drop_column('rough_ideas_dump')
        batch_op.drop_column('goal')

    # ### end Alembic commands ###
